export const TYPES_MAP = {
  Тонкое: "light",
  Толстое: "large",
  Томатный: "tomato",
  Сливочный: "creamy",
  Грибы: "mushrooms",
  Чеддер: "cheddar",
  Салями: "salami",
  Ветчина: "ham",
  Ананас: "ananas",
  Бекон: "bacon",
  Лук: "onion",
  Чили: "chile",
  Халапеньо: "jalapeno",
  Томаты: "tomatoes",
  Лосось: "salmon",
  Моцарелла: "mozzarella",
  Пармезан: "parmesan",
  Маслины: "olives",
  "Блю чиз": "blue_cheese",
  "23 см": "small",
  "32 см": "normal",
  "45 см": "big",
};
